# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Karoline de Alencar
email: karolinedalencar@gmail.com
description: "Blog sobre desenvolvimento web."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karolinedealencar.com.br" # the base hostname & protocol for your site
twitter_username: karoldalencar
github_username:  KarolinedeAlencar
plugins: [jekyll-paginate]
paginate: 6
paginate_path: "pagina/:num/"

# Build settings
markdown: kramdown
permalink: /:title
